SUPABASE_URL = "https://qjtugyltzyhoeuiraznn.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqdHVneWx0enlob2V1aXJhem5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1NzA5OTMsImV4cCI6MjA1NzE0Njk5M30.y2nSZtRU-FsqZvkhJhsAKfYLzbbplYgpVQp0MJMViXE"
